[[redirects]]
  from = "/"
  to = "/404"
  status = 403
  force = false
  query = {path = ":path"}
  conditions = {Language = ["zh", "ru", "hi"], Country = ["CN", "RU", "IN", "TR", "TW", "HK", "MO", "BR", "MY", "ID", "UA"]}
